# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HuginCyber.hugin
PackageVersion: 0.4.43
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Commands:
  - hugin
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/HuginCyber/Hugin/releases/download/v0.4.43/hugin-cli-windows-x86_64.exe
    InstallerSha256: 08516FE69A432E9262FAC0E615DC4CC908F0E1D952076CCCCC10F230454EEC61
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-08
